### ISSUE TITLE
Code clean-up

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ProbeParticleModel#12]
There seems to be a lot of unused code and old/alternative versions of functions and modules that could probably be deleted. Additionally, some things could be renamed and reorganized to be cleaner. I'm afraid to just go and delete things, so I'll list here the things that I would change, and we can discuss it.

- [x] #19
- [x] #24
- [x] #25
- [x] #23
- [x] #18
- [x] #20
- [x] #21
- [x] #22
- [x] #26

**Comment by NikoOinonen** [comment]
I also tried running flake8 to detect problems in the code. The report is in the attachment. There seems to be many cases (113) of undefined variables and a couple of syntax errors. These lines of code will never run, so I guess they have never been tested or are remainders from earlier versions. Maybe @ProkopHapala could look through these to see if they should be fixed or just deleted.

[flake8_test.txt](https://github.com/Probe-Particle/ProbeParticleModel/files/9695577/flake8_test.txt)

**Comment by ProkopHapala** [comment]
> [flake8_test.txt](https://github.com/Probe-Particle/ProbeParticleModel/files/9695577/flake8_test.txt)
Thank you Niko,  I did not know about such tool

**Comment by NikoOinonen** [comment]
All of the listed issues have been resolved, so closing this issue.
