### ISSUE TITLE
Clean-up repository root

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ProbeParticleModel#22]
There are a lot of scripts in the root of the repository. Are all of these necessary? In my opinion, only the most important ones (generateLJFF.py etc.) should be here, and put the other ones into some sub-directory to make it more clear.

**Comment by yakutovicha** [comment]
@ProkopHapala will prepare a list of scripts and a short description what they are doing.

**Comment by ProkopHapala** [comment]
So I documented what each of the script do (also context why it was created and by whom) suggested some action and serted into categories.

https://github.com/Probe-Particle/ProbeParticleModel/wiki/Root-Scripts

I have some points to discus:

1. @yakutovicha  have 3 scripts there he used in his paper about fitting PPM to DFT reference. Do you thing it is still somehow usefull or should we delete it?
2. @NikoOinonen do you have idea if `GUILJ.py` and `GUIMorse.py` are still both usefull after you remastered it? Cannot we merge it into one GUI?
3. @NikoOinonen  do you have idea if any of `runOpenCLBatch_*.py` is still usefull? I think we should keep just one or delete all.
4. @ Everybody - I think there are some scripts I would sort into `utils` and `dev` and `GUI` category. Utils are generally usefull but not essential for running probe particle jobs.  `dev` are work-in-progress. GUI are GUI so I'm not sure if they should be together with the other scripts?  Question is - should we put them into some separate folders? 
5. Scripts in category `Other` I would perhaps simply delete.

**Comment by NikoOinonen** [comment]
>     2. @NikoOinonen do you have idea if `GUILJ.py` and `GUIMorse.py` are still both usefull after you remastered it? Cannot we merge it into one GUI?

I did all of my development in GUILJ.py (which will get renamed to ppm-gui once PR#29 gets merged). I did not touch GUIMorse.py, and I'm guessing it's broken at the moment. I would say we just delete GUIMorse.py now and if we want to add the Morse potential as an option to the GUI, then that should be it's own issue.

>     3. @NikoOinonen  do you have idea if any of `runOpenCLBatch_*.py` is still usefull? I think we should keep just one or delete all.

I don't even remember what these are for. Probably just delete them. If there is something useful there for later, then it can be found in the git history.

>     4. @ Everybody - I think there are some scripts I would sort into `utils` and `dev` and `GUI` category. Utils are generally usefull but not essential for running probe particle jobs.  `dev` are work-in-progress. GUI are GUI so I'm not sure if they should be together with the other scripts?  Question is - should we put them into some separate folders?

I think it makes sense to have a separate GUI folder, since they are quite different from the other scripts.

On a related note, it would probably make sense to merge the functionality of generateElFF_point_charges.py into generateElFF.py, but that should be it's own issue and not urgent. Also maybe merge relaxed_scan_PVE.py into relaxed_scan.py?

**Comment by yakutovicha** [comment]
> 1. @yakutovicha  have 3 scripts there he used in his paper about fitting PPM to DFT reference. Do you thing it is still somehow usefull or should we delete it?

Those are in the `complex_tip` branch, right? I will take care of dealing with this branch later.

**Comment by ondrejkrejci** [comment]
My ideas/comments/suggestions:
- Merge: `generateElFF_point_charges.py` into `generateElFF.py`
- Move everything that you had commented as _Utils_ into some `utilities` folder, but change the scripts paths in the import header sections, so they work immediately.
- Adding `fitPauli.py` into `untilities` folder, succesfully used in one of our manuscript.
 - `GUILJ.py` should be renamed to `GUI.py` and it should stay in the root. We should have it so it would be found as simple as possible, as most of the non-developers will work with it in the future.
 - `GUImorse.py` should be removed, it was not working since like 2019.
 - `ExpShifter.py` and `Viewer.py` should go to utils. 
 - `plot_slices_dat.py` - I would add it into `utilities` folder.
 I either agree with you, or do not have any other ideas on the **Other** and **Dev** scripts ...

**Comment by NikoOinonen** [comment]
> Move everything that you had commented as Utils into some utilities folder, but change the scripts paths in the import header sections, so they work immediately.
GUILJ.py should be renamed to GUI.py and it should stay in the root. We should have it so it would be found as simple as possible, as most of the non-developers will work with it in the future.

As far as I understood, it does not matter where the files are in the repo, because after we get it to install with pip it will also install the scripts so that you can run them from anywhere in the terminal.

**Comment by yakutovicha** [comment]
@ProkopHapala would you be able to work on this? Or should someone else take this task?

**Comment by ProkopHapala** [comment]
I can do it perhaps next week
