### ISSUE TITLE
Wrong step size in energy/force calculation

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ProbeParticleModel#38]
I ran into this a while ago and again recently when comparing the energy calculated by generateElFF.py and the energy that I got using the OpenCL code. The result is different by a tiny amount and makes practically no difference to the resulting images, but it's something that has been causing me some pain in testing the OpenCL implementation.

The problem stems from the function `getSize` in fieldFFT.py that is used for getting the grid size and step: https://github.com/Probe-Particle/ProbeParticleModel/blob/a97b04adcfea4228384c4bd946001599c34b4a83/pyProbeParticle/fieldFFT.py#L19-L25 I believe there in that last line it should be simply `size/dims[axis]` instead of `size/(dims[axis] - 1)`. This has probably been written with the assumption of the one extra grid step that .xsf files have. However, the `loadXSF` function already subracts this one extra step since this commit: https://github.com/Probe-Particle/ProbeParticleModel/commit/d7f723a2fa549fc2736aae7ba264d3d39e3eef42 https://github.com/Probe-Particle/ProbeParticleModel/blob/a97b04adcfea4228384c4bd946001599c34b4a83/pyProbeParticle/GridUtils.py#L252 

Maybe @ProkopHapala and/or @ondrejkrejci could confirm that this is correct?

**Comment by ondrejkrejci** [comment]
Hi, I needed to even make image on it. And I believe that your assumptions is right.
**But** - we debugged the code many times, regarding issues of grid boundaries, as we ran into them in the past. Before changing it, I would suggest to print this while running the PTCDA and graphene example. And calculate it also by hand, to see if it is working right or wrong. Thank you!

**Comment by NikoOinonen** [comment]
For the PTCDA Hartree example, we have this grid specification:
```
BEGIN_DATAGRID_3D_LOCPOT_v2xsf
   253    169    281
   0.000000    0.000000    0.000000
   18.964100    0.000000    0.000000
   0.000000    12.605900    0.000000
   0.000000    0.000000    20.000000
```
According to the xsf format specification (http://www.xcrysden.org/doc/XSF.html#__toc__11), the grid is explicitly non-periodic, so we have one less step than the number of points, so it's 252, 168, and 280 steps in the x, y, and z directions. If we divide the side lengths by these numbers, then we get step sizes  `0.07525436, 0.07503511, 0.07142857`. But if I print out the step sizes that come out from `getSize` while running `generateElFF.py`, those are `0.07555418, 0.07548443, 0.07168458`. The difference is tiny, but if I remove the `-1`, then they match up exactly.

This is seen even more easily with cube files where the step size is written into the file itself, and it does not match up without removing that `-1`.

The graphene example is with point-charges, which does not use `getSize` to calculate the step size.

**Comment by ondrejkrejci** [comment]
I see, good. Please could you run the PTCDA tests for both - the original and repaired part and check the outputs (and maybe FFel_z.xsf in Vesta). If the new ones looks good/better (maybe attach an image in the next comment), then I can be a reviewer for the pull_request/merge. Thank you for spotting it!

**Comment by ondrejkrejci** [comment]
The difference is totally different then I expected. I thought, that there would be some distortions. Well, anyway, thank you for spotting it.
