### ISSUE TITLE
Add `__init__.py` to ppafm submodules

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ProbeParticleModel#58]
Otherwise, the modules are not included in the package release.

**Comment by NikoOinonen** [comment]
If I'm reading the [setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery) correctly, it should be enough to just enable implicit namespaces, which we have disabled in the `pyproject.toml`: https://github.com/Probe-Particle/ProbeParticleModel/blob/c8c6f1a253abbfdff671c6384c1525f50e226d13/pyproject.toml#L43-L44 I would just remove that, unless we have some reason to disable implicit namespaces.

**Comment by yakutovicha** [comment]
> I would just remove that, unless we have some reason to disable implicit namespaces.

I fear it might include an unwanted folder in the distribution - but I don't know, tbh.

Maybe just try to build the package locally and see what is contained in the package, as explained at the [end of the section](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-namespace-packages).

**Comment by NikoOinonen** [comment]
I found that you can specify which packages to include in `pyproject.toml` by using the `include` key in `tool.setuptools.packages.find`:
```toml
[tool.setuptools.packages.find]
include = [
    "ppafm",
    "ppafm.defaults",
    "ppafm.ocl",
    "ppafm.ml"
]
```
It requires listing out all of the modules and submodules, but I think it's still a bit cleaner than adding empty files. I created a PR with the change #59

**Comment by yakutovicha** [comment]
> > I would just remove that, unless we have some reason to disable implicit namespaces.
> 
> I fear it might include unwanted folders in the distribution - but I don't know, tbh.
> 
> Maybe just try to build the package locally and see what is contained in the package, as explained at the [end of the section](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-namespace-packages).

Ok, just for the record: I tried to set `find = {namespaces = true}` and run `python -m build`. The produced archive (`ppafm-0.1.0.tar.gz`) contained every folder in from the repo:

```bash
.
├── GUI
│   ├── ExpShifter.py
│   ├── ExpShifter_2tips.py
│   └── Viewer.py
├── PKG-INFO
├── README.md
├── dev
│   ├── FARFF
│   │   └── test_FARFF_AuxMaps.py
│   ├── bakup
│   │   ├── GUImorse.py
│   │   ├── conv_rho_mini.py
│   │   ├── runOpenCLbatch.py
│   │   ├── runOpenCLbatchRot.py
│   │   ├── runOpenCLbatchRot2.py
│   │   ├── runOpenCLbatchRot_class.py
│   │   ├── subChgCore.py
│   │   └── subChgCore_cpp.py
│   ├── compress_rho.py
│   ├── convolvePot.py
│   ├── fitMultipoles.py
│   ├── fitPPM
│   │   ├── fitting.py
│   │   ├── plotLine.py
│   │   └── plotZ.py
│   ├── fitPauli.py
│   ├── testFieldOCL
│   │   ├── GUI.py
│   │   ├── clImage3D.py
│   │   ├── testOpenCL_2.py
│   │   ├── testRelaxOpenCL.py
│   │   └── test_fileIO.py
│   ├── testMultipole.py
│   ├── testMultipole2.py
│   ├── testTipForce.py
│   ├── test_MMFF.py
│   ├── test_PolyCycles.py
│   ├── test_PolyCycles2.py
│   ├── test_PolyCycles3.py
│   ├── test_ReactiveFF.py
│   ├── test_atomicUtils.py
│   ├── test_io.py
│   └── test_splines.py
├── doc
│   └── sphinx
│       └── source
│           └── conf.py
├── examples
│   ├── CorrectionLoopGraphene
│   │   └── test_CorrectionLoop.py
│   ├── Generator
│   │   └── test_trainer.py
│   ├── Graphene_mod
│   │   ├── AutoSegmentImage.py
│   │   ├── fitAtoms.py
│   │   └── fitAtoms2.py
│   ├── PTCDA_Hartree
│   │   ├── run_gpu.py
│   │   └── run_gpu_easy.py
│   ├── PTCDA_Hartree_dz2
│   │   └── tip.py
│   └── _bak
│       ├── afm.py
│       ├── hartree_carbox
│       │   ├── test_hartree_watter_QKscan.py
│       │   └── test_loadXsf.py
│       ├── ppr
│       │   ├── hartree2FFs.py
│       │   └── ppr.new.py
│       ├── testServer2.py
│       └── watter_monomer_4fold
│           ├── LJ_4fold.py
│           ├── locpot_4fold.py
│           ├── relaxed_scan.py
│           └── relaxed_scanQK.py
├── ppafm
│   ├── CG.py
│   ├── COvsCO.py
│   ├── FARFF.py
│   ├── GLView.py
│   ├── GUIWidgets.py
│   ├── GridUtils.py
│   ├── HighLevel.py
│   ├── MMFF.py
│   ├── Multipoles.py
│   ├── PPPlot.py
│   ├── PolyCycles.py
│   ├── ReactiveFF.py
│   ├── RigidMol.py
│   ├── SimplePot.py
│   ├── SurfConf.py
│   ├── __init__.py
│   ├── atomfit.py
│   ├── atomicUtils.py
│   ├── basUtils.py
│   ├── chemistry.py
│   ├── common.py
│   ├── core.py
│   ├── cpp_utils.py
│   ├── defaults
│   │   └── valelec_dict.py
│   ├── elements.py
│   ├── fieldFFT.py
│   ├── file_dat.py
│   ├── fitSpline.py
│   ├── fitting.py
│   ├── ml
│   │   ├── AuxMap.py
│   │   ├── CorrectionLoop.py
│   │   ├── Corrector.py
│   │   └── Generator.py
│   ├── ocl
│   │   ├── AFMulator.py
│   │   ├── field.py
│   │   ├── oclUtils.py
│   │   └── relax.py
│   └── version.py
├── ppafm.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── not-zip-safe
│   ├── requires.txt
│   └── top_level.txt
├── pyproject.toml
├── setup.cfg
└── utilities
    ├── cube2xsf.py
    ├── evalFFLine.py
    ├── extract_desities.py
    ├── fitFz.py
    ├── plotQuad.py
    ├── plotZcurves.py
    ├── plot_slices_dat.py
    └── xsf2png.py
```

I would assume that we don't want this. For instance, we don't want to have `examples` and test folders distributed with the package. Let me know if you disagree.

**Comment by yakutovicha** [comment]
> I found that you can specify which packages to include in pyproject.toml by using the include key in tool.setuptools.packages.find:

I am confused here. The approach you are proposing here is not super-standard. It is used to create [`namespace packages`](https://peps.python.org/pep-0420/). I was not aware of those types of packages, but after reading the documentation I understood that they are a way of splitting a module across multiple directories on disk. I am not sure we need that. Here is what the [documentation says](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/):

```
Namespace packages can be useful for a large collection of loosely-related packages (such as a large corpus of client
libraries for multiple products from a single company). However, namespace packages come with several caveats and
are not appropriate in all cases.
```

> It requires listing out all of the modules and submodules, but I think it's still a bit cleaner than adding empty files. I created a PR with the change #59

I don't understand why explicit specification of modules `pyproject.toml` is beneficial. I already see people forgetting to put folders in the `pyproject.toml` file and wondering what went wrong and why modules are missing in the distribution. Also, typically those `__init__.py` files are not empty. They contain the module API.

**Conclusion**

I think if one wants to adopt a non-standard approach - one needs to have a very clear justification for why this is beneficial. The benefits are not unclear to me. Herein, I prefer to use `__init__.py` to convert a folder to a module.

**Comment by NikoOinonen** [comment]
Ok, I didn't know the difference. It worked as expected when I did the local build. I'll just put the `__init__.py` files there.
